### PR TITLE
Map screen

### LINKED ISSUE #8: feature/map_screen: As a user I want to interact with the game map by opening it and selecting one of my characters to move around the map.
For now, the map screen will use a static image.

- [x] ***Prepare map page***

   - Create a Jinja2 template with a map
   - Add basic style to the map screen
   - Add navigation to map screen (route and user menu)

- [x] ***Add character icon functionality***
  
   - Add a mock icon with placeholder name and stats
   - Write JS for adding and moving the mock icon on the map
   - Allow user to select a character to display on the map
   - Connect the character info to the player icon

- [x] ***Improve app look***

   - Add simple styling to the app
   - Make sure the style is uniform throughout

- [x] ***Code cleanup***

   - Refactor added code to fit principles of DX
   - Logic separation where needed

### PR DESCRIPTION
**Pull request by stenvma81**
- Added a map screen where the user can move his player icon over a map and choose  which of his created characters is linked to the icon. The icon maintains its position relative to the map when browser window is resized and map size changes.
- Added basic CSS to the app
- Refactored some code to improve readability
- Token and form related functions moved to /utils

Closes #8

### CODE REVIEW

**Comment by w1000w** [comment]
The application seems to be some type of helper for players of tabletop RPGs, what that actually entails isn't quite clear to me (as I don't play tabletop RPGs).

The codebase is nicely organized and pretty easy to understand. The naming is mostly consistent and clear.

I think the commits could be slightly more atomic and seem to cover more features than needed. You may also want to separate styling to separate commits, it can be bit of a pain in the ass to read through the styling changes at times.

Have you thought about using some prebuilt library for managing CSRF tokens? Could Flask's 'before_request' decorator help deal with the repeated calls to 'get_csrf_token()'?

Is there a particular reason event listeners are not being used here? Personally I find them easier to read and pick up from the code.
```
draggableElement.onmousedown = initiateDrag;
```

For routing, Flask blueprints could make sense, especially if the programs continues to grow as it would allow you to modularize your code going forward.

**Comment by stenvma81** [comment]
@w1000w 

> I think the commits could be slightly more atomic and seem to cover more features than needed. You may also want to separate styling to separate commits, it can be bit of a pain in the ass to read through the styling changes at times.

Yep, large commits are my biggest sin. I'm not approaching this project in an organized manner. There is no actual backlog and in my head I always want to add extra tasks when working with each feature. The styling of the app could have been done as an individual task in its own branch. It is often no small undertaking and takes a bit of experimentation.

> Have you thought about using some prebuilt library for managing CSRF tokens? Could Flask's 'before_request' decorator help deal with the repeated calls to 'get_csrf_token()'?

No, I have been too focused on getting the features done to actually do some refactoring on those. I'll be sure to give it a look if I end up switching to Flask Blueprints.

> Is there a particular reason event listeners are not being used here? Personally I find them easier to read and pick up from the code.
> 
> ```
> draggableElement.onmousedown = initiateDrag;
> ```

Yes. I haven't written JS in a while and wanted to do it as much from memory as possible. I also want to invoke as many comments on my coding style as possible so I'm not exactly trying to avoid unorthodox solutions and convolutions of habit.

> For routing, Flask blueprints could make sense, especially if the programs continues to grow as it would allow you to modularize your code going forward.

Yeah, that point has been made earlier. Modularization is the way to go pretty much always, but for some reason I don't like the way Flask Blueprints work. Maybe because I don't want to fracture my routing... I might make this my next week's refactoring target though and leave the next feature for later.

Thanks for the comment!

**Comment by elenabli** [comment]
Well, the previous commenter wrote pretty much everything that came to my mind as well. I'll still write my observations, but you don't have to respond to them, since I've already read the responses to the previous review myself.

The code is quite readable and well-structured, but I'm having trouble grasping the app's purpose from the README. The title hints at something for gamers, but the details are a bit elusive. I'm not an RPG player, so it might not be my cup of tea. Any chance we can get a bit more clarity in the README? Thanks a bunch!

image

My personal opinion: commits should be short :) if a commit message is so long that you have to expand it to get the gist of it, it's probably better to split it into a couple of commits. The second commit on the screenshot is the best!


image

Here it seems to be two different routes. You have defined the modify_character_get route twice with the same URL pattern. Should it be `POST` in a second route? What is the purpose of those route?


You use here the `onmousedown`
image

And here `addEventListener`
image

Why not just bring it to one view and use `addEventListener` when required for better flexibility and compatibility? Is there any particular purpose for using `onmousedown` and `onmouseup` specifically? I would also add `window.onload` here, but not sure about it.

And to wrap it up: great job! Really!

**Comment by stenvma81** [comment]
@elenabli

> The code is quite readable and well-structured, but I'm having trouble grasping the app's purpose from the README. The title hints at something for gamers, but the details are a bit elusive. I'm not an RPG player, so it might not be my cup of tea. Any chance we can get a bit more clarity in the README? Thanks a bunch!

The purpose of the app is explained with the feature list but yes, it could also be in the initial description. I will look into changing it before merging to main.

> image
> My personal opinion: commits should be short :) if a commit message is so long that you have to expand it to get the gist of it, it's probably better to split it into a couple of commits. The second commit on the screenshot is the best!

That's also my view of the commit messages, but for the sake of DX I added more descriptive messages. Maybe it would be a good idea to fit a concrete "what was done" on the visible line and then the how and why can be viewed when expanded.

> Here it seems to be two different routes. You have defined the modify_character_get route twice with the same URL pattern. Should it be `POST` in a second route? What is the purpose of those route?

Yeah, that's a lapse on my part. For some reason the GET that is supposed to be POST still works. Weird.

> Why not just bring it to one view and use `addEventListener` when required for better flexibility and compatibility? Is there any particular purpose for using `onmousedown` and `onmouseup` specifically? I would also add `window.onload` here, but not sure about it.

Nah, it's just me being tired and trying to write JS without the help of any documentation. Don't remember anymore, but I'm pretty sure this choice was a quick patch to avoid some quirk in the functionality in the code. I might return to this when I start to work on the multiple user session.

**Pull request merged**
